### ISSUE TITLE
Multiple option arguments

### ISSUE THREAD

**Issue by kbknapp** [archer884/recurrence_relations#1]
I noticed the readme in your repo saying you wanted to use clap's `occurrences_of()` for multiple options. I've just uploaded another version to crates.io that supports this (well via `values_of()` [notice the **s**]). I haven't spent much time documenting but basic premise is (which I have no doubt you would have guessed - I'm pretty sure you're more comfortable with Rust than I am after seeing your code ;) ):

``` rust
Arg::new("option").short("o").multiple(true).takes_value(true)
// ...

if let Some(ref opts) = matches.values_of("option") {
    for opt in opts.iter() {
        println!("O: {}", opt);
    }
}
println!("Number of options: {}", matches.occurrences_of("option"));
// running with "myapp -o lots -o of -o strings" prints
// O: lots
// O: of
// O: strings
// Number of options: 3
```

Totally cool if you want to continue with a specialized fork too, or if it's still not quite what you're looking for, that's the beauty of open source :) And yep, still under VERY heavy flux, but hopefully I'll come out the other end in one piece!

Best of luck, and thanks for the use!

**Comment by archer884** [comment]
Holy crap, that's awesome. I had been thinking about how to best go about adding that to your library, but the reason I forked it was to experiment with a typed version of value_of (you might notice that branch in my fork). I implemented it, but I decided (this is even in the commit message) that it added so little value to what you already have as to be practically pointless.

Your arg parser is easily the best I have used for Rust and I'm very glad to see it still improving. I'll have to update the solution here to use that just to show it off. :P
